import { Component } from '@angular/core';

@Component({
  selector: 'app-chart',
  templateUrl: './chart.component.html',
  styleUrl: './chart.component.css',
})
export class ChartComponent {
  public data = [
    {
      agent: 'karthik',
      Exit: 1,
      Interaction: 3,
      CustomerNo: 6,
      UniqNumber: 88,
      Tic: 55,
      Ac: 44,
      TOBC: 55,
    },
    {
      agent: 'karthik',
      Exit: 1,
      Interaction: 3,
      CustomerNo: 6,
      UniqNumber: 88,
      Tic: 55,
      Ac: 44,
      TOBC: 55,
    },
    {
      agent: 'karthik',
      Exit: 1,
      Interaction: 3,
      CustomerNo: 6,
      UniqNumber: 88,
      Tic: 55,
      Ac: 44,
      TOBC: 55,
    },
    {
      agent: 'karthik',
      Exit: 1,
      Interaction: 3,
      CustomerNo: 6,
      UniqNumber: 88,
      Tic: 55,
      Ac: 44,
      TOBC: 55,
    },
    {
      agent: 'karthik',
      Exit: 1,
      Interaction: 3,
      CustomerNo: 6,
      UniqNumber: 88,
      Tic: 55,
      Ac: 44,
      TOBC: 55,
    },
    {
      agent: 'karthik',
      Exit: 1,
      Interaction: 3,
      CustomerNo: 6,
      UniqNumber: 88,
      Tic: 55,
      Ac: 44,
      TOBC: 55,
    },
    {
      agent: 'karthik',
      Exit: 1,
      Interaction: 3,
      CustomerNo: 6,
      UniqNumber: 88,
      Tic: 55,
      Ac: 44,
      TOBC: 55,
    },
    {
      agent: 'karthik',
      Exit: 1,
      Interaction: 3,
      CustomerNo: 6,
      UniqNumber: 88,
      Tic: 55,
      Ac: 44,
      TOBC: 55,
    },
    {
      agent: 'karthik',
      Exit: 1,
      Interaction: 3,
      CustomerNo: 6,
      UniqNumber: 88,
      Tic: 55,
      Ac: 44,
      TOBC: 55,
    },
    {
      agent: 'karthik',
      Exit: 1,
      Interaction: 3,
      CustomerNo: 6,
      UniqNumber: 88,
      Tic: 55,
      Ac: 44,
      TOBC: 55,
    },
    {
      agent: 'karthik',
      Exit: 1,
      Interaction: 3,
      CustomerNo: 6,
      UniqNumber: 88,
      Tic: 55,
      Ac: 44,
      TOBC: 55,
    },
    {
      agent: 'karthik',
      Exit: 1,
      Interaction: 3,
      CustomerNo: 6,
      UniqNumber: 88,
      Tic: 55,
      Ac: 44,
      TOBC: 55,
    },
    {
      agent: 'karthik',
      Exit: 1,
      Interaction: 3,
      CustomerNo: 6,
      UniqNumber: 88,
      Tic: 55,
      Ac: 44,
      TOBC: 55,
    },
    {
      agent: 'karthik',
      Exit: 1,
      Interaction: 3,
      CustomerNo: 6,
      UniqNumber: 88,
      Tic: 55,
      Ac: 44,
      TOBC: 55,
    },
    {
      agent: 'karthik',
      Exit: 1,
      Interaction: 3,
      CustomerNo: 6,
      UniqNumber: 88,
      Tic: 55,
      Ac: 44,
      TOBC: 55,
    },
    {
      agent: 'karthik',
      Exit: 1,
      Interaction: 3,
      CustomerNo: 6,
      UniqNumber: 88,
      Tic: 55,
      Ac: 44,
      TOBC: 55,
    },
    {
      agent: 'karthik',
      Exit: 1,
      Interaction: 3,
      CustomerNo: 6,
      UniqNumber: 88,
      Tic: 55,
      Ac: 44,
      TOBC: 55,
    },
    {
      agent: 'karthik',
      Exit: 1,
      Interaction: 3,
      CustomerNo: 6,
      UniqNumber: 88,
      Tic: 55,
      Ac: 44,
      TOBC: 55,
    },
    {
      agent: 'karthik',
      Exit: 1,
      Interaction: 3,
      CustomerNo: 6,
      UniqNumber: 88,
      Tic: 55,
      Ac: 44,
      TOBC: 55,
    },
    {
      agent: 'karthik',
      Exit: 1,
      Interaction: 3,
      CustomerNo: 6,
      UniqNumber: 88,
      Tic: 55,
      Ac: 44,
      TOBC: 55,
    },
    {
      agent: 'karthik',
      Exit: 1,
      Interaction: 3,
      CustomerNo: 6,
      UniqNumber: 88,
      Tic: 55,
      Ac: 44,
      TOBC: 55,
    },
    {
      agent: 'karthik',
      Exit: 1,
      Interaction: 3,
      CustomerNo: 6,
      UniqNumber: 88,
      Tic: 55,
      Ac: 44,
      TOBC: 55,
    },
  ];
}
